name: Display Secret
on: [push]

jobs:
  display-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display ACCOUNTS_JSON from Secrets
        run: |
          echo "SSH_INFO content:"
          printf "%s\n" "${{ secrets.SSH_INFO }}"
